/*
 * Copyright (c) 2025 - Nathanne Isip
 * This file is part of Netlet.
 *
 * Netlet is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * Netlet is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Netlet. If not, see <https://www.gnu.org/licenses/>.
 */

#include <netlet/net/mime.hpp>

#include <algorithm>
#include <map>

namespace Netlet::Net {

std::string get_mime_type(const std::string &filename) {
  static const std::map<std::string, std::string> mimeTypes = {
      // Common Text Files
      {".txt", "text/plain"},
      {".html", "text/html"},
      {".htm", "text/html"},
      {".css", "text/css"},
      {".js", "application/javascript"},
      {".json", "application/json"},
      {".xml", "text/xml"},
      {".csv", "text/csv"},
      {".tsv", "text/tab-separated-values"},
      {".md", "text/markdown"},
      {".log", "text/plain"},
      {".ini", "text/plain"},
      {".conf", "text/plain"},
      {".yaml", "text/yaml"},
      {".yml", "text/yaml"},

      // Image Files
      {".jpg", "image/jpeg"},
      {".jpeg", "image/jpeg"},
      {".png", "image/png"},
      {".gif", "image/gif"},
      {".bmp", "image/bmp"},
      {".webp", "image/webp"},
      {".ico", "image/x-icon"},
      {".svg", "image/svg+xml"},
      {".tiff", "image/tiff"},
      {".tif", "image/tiff"},
      {".heic", "image/heic"},
      {".avif", "image/avif"},

      // Audio Files
      {".mp3", "audio/mpeg"},
      {".wav", "audio/wav"},
      {".ogg", "audio/ogg"},
      {".flac", "audio/flac"},
      {".aac", "audio/aac"},
      {".m4a", "audio/mp4"},
      {".opus", "audio/opus"},

      // Video Files
      {".mp4", "video/mp4"},
      {".avi", "video/x-msvideo"},
      {".mov", "video/quicktime"},
      {".wmv", "video/x-ms-wmv"},
      {".flv", "video/x-flv"},
      {".webm", "video/webm"},
      {".mkv", "video/x-matroska"},
      {".3gp", "video/3gpp"},
      {".ts", "video/mp2t"},

      // Document Files
      {".pdf", "application/pdf"},
      {".doc", "application/msword"},
      {".docx", "application/"
                "vnd.openxmlformats-officedocument.wordprocessingml.document"},
      {".xls", "application/vnd.ms-excel"},
      {".xlsx",
       "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"},
      {".ppt", "application/vnd.ms-powerpoint"},
      {".pptx",
       "application/"
       "vnd.openxmlformats-officedocument.presentationml.presentation"},
      {".odt", "application/vnd.oasis.opendocument.text"},
      {".ods", "application/vnd.oasis.opendocument.spreadsheet"},
      {".odp", "application/vnd.oasis.opendocument.presentation"},
      {".rtf", "application/rtf"},

      // Archive Files
      {".zip", "application/zip"},
      {".tar", "application/x-tar"},
      {".gz", "application/gzip"},
      {".tgz", "application/gzip"},
      {".bz2", "application/x-bzip2"},
      {".rar", "application/x-rar-compressed"},
      {".7z", "application/x-7z-compressed"},
      {".iso", "application/x-iso9660-image"},

      // Executables and Binaries
      {".exe", "application/x-ms-dos-executable"},
      {".dll", "application/x-msdownload"},
      {".bin", "application/octet-stream"},
      {".deb", "application/x-debian-package"},
      {".rpm", "application/x-rpm"},
      {".dmg", "application/x-apple-diskimage"},
      {".apk", "application/vnd.android.package-archive"},

      // Programming Language Source Files
      {".c", "text/x-c"},
      {".cpp", "text/x-c++"},
      {".h", "text/x-c"},
      {".hpp", "text/x-c++"},
      {".java", "text/x-java-source"},
      {".py", "text/x-python"},
      {".rb", "text/x-ruby"},
      {".php", "application/x-php"},
      {".pl", "text/x-perl"},
      {".sh", "application/x-sh"},
      {".bat", "application/x-msdownload"},
      {".ps1", "application/x-powershell"},
      {".go", "text/x-go"},
      {".rs", "text/x-rust"},
      {".swift", "text/x-swift"},
      {".kt", "text/x-kotlin"},
      {".ts", "application/typescript"},
      {".jsx", "text/jsx"},
      {".tsx", "text/tsx"},
      {".vue", "text/x-vue"},
      {".json5", "application/json5"},
      {".toml", "application/toml"},

      // Fonts
      {".ttf", "font/ttf"},
      {".otf", "font/otf"},
      {".woff", "font/woff"},
      {".woff2", "font/woff2"},
      {".eot", "application/vnd.ms-fontobject"},

      // Web Assembly
      {".wasm", "application/wasm"},

      // Scientific/Data Formats
      {".hdf5", "application/x-hdf5"},
      {".h5", "application/x-hdf5"},
      {".feather", "application/vnd.apache.arrow.file"},
      {".parquet", "application/vnd.apache.parquet"},

      // Other common types
      {".sql", "application/sql"},
      {".db", "application/octet-stream"},
      {".sqlite", "application/vnd.sqlite3"},
      {".vcf", "text/vcard"},
      {".ics", "text/calendar"},
      {".eps", "application/postscript"},
      {".ps", "application/postscript"},
      {".ai", "application/postscript"},
      {".psd", "image/vnd.adobe.photoshop"},
      {".indd", "application/x-indesign"},
      {".xfdf", "application/vnd.adobe.xfdf"},
      {".fdf", "application/vnd.fdf"},
      {".xul", "application/vnd.mozilla.xul+xml"},
      {".rdf", "application/rdf+xml"},
      {".rss", "application/rss+xml"},
      {".atom", "application/atom+xml"},
      {".kml", "application/vnd.google-earth.kml+xml"},
      {".kmz", "application/vnd.google-earth.kmz"},
      {".gpx", "application/gpx+xml"},
      {".geojson", "application/geo+json"},
      {".topojson", "application/topojson"},
      {".dwg", "image/vnd.dwg"},
      {".dxf", "image/vnd.dxf"},
      {".iges", "model/iges"},
      {".igs", "model/iges"},
      {".obj", "model/obj"},
      {".stl", "model/stl"},
      {".dae", "model/vnd.collada+xml"},
      {".fbx", "application/octet-stream"},
      {".gltf", "model/gltf+json"},
      {".glb", "model/gltf-binary"},
      {".step", "application/step"},
      {".stp", "application/step"},
      {".ifc", "application/ifc"},
      {".vsd", "application/vnd.visio"},
      {".vsdx", "application/vnd.ms-visio.drawing"},
      {".mpp", "application/vnd.ms-project"},
      {".mpt", "application/vnd.ms-project"},
      {".msg", "application/vnd.ms-outlook"},
      {".pst", "application/vnd.ms-outlook"},
      {".eml", "message/rfc822"},
      {".oft", "application/vnd.ms-outlook"},
      {".xps", "application/vnd.ms-xpsdocument"},
      {".oxps", "application/oxps"},
      {".xaml", "application/xaml+xml"},
      {".xap", "application/x-silverlight-app"},
      {".swf", "application/x-shockwave-flash"},
      {".flac", "audio/flac"},
      {".mid", "audio/midi"},
      {".midi", "audio/midi"},
      {".rmi", "audio/midi"},
      {".kar", "audio/midi"},
      {".voc", "audio/x-voc"},
      {".aif", "audio/x-aiff"},
      {".aiff", "audio/x-aiff"},
      {".au", "audio/basic"},
      {".snd", "audio/basic"},
      {".ra", "audio/x-pn-realaudio"},
      {".ram", "audio/x-pn-realaudio"},
      {".rm", "application/vnd.rn-realmedia"},
      {".rpm", "audio/x-pn-realaudio-plugin"},
      {".asf", "video/x-ms-asf"},
      {".asx", "video/x-ms-asf"},
      {".m3u", "audio/x-mpegurl"},
      {".m3u8", "application/vnd.apple.mpegurl"},
      {".pls", "audio/x-scpls"},
      {".wax", "audio/x-ms-wax"},
      {".wma", "audio/x-ms-wma"},
      {".wvx", "video/x-ms-wvx"},
      {".dvi", "application/x-dvi"},
      {".latex", "application/x-latex"},
      {".tex", "application/x-tex"},
      {".texi", "application/x-texinfo"},
      {".texinfo", "application/x-texinfo"},
      {".chm", "application/vnd.ms-htmlhelp"},
      {".hlp", "application/winhlp"},
      {".dot", "application/msword"},
      {".dotx", "application/"
                "vnd.openxmlformats-officedocument.wordprocessingml.template"},
      {".xlt", "application/vnd.ms-excel"},
      {".xltx",
       "application/vnd.openxmlformats-officedocument.spreadsheetml.template"},
      {".pot", "application/vnd.ms-powerpoint"},
      {".potx",
       "application/vnd.openxmlformats-officedocument.presentationml.template"},
      {".pps", "application/vnd.ms-powerpoint"},
      {".ppsx", "application/"
                "vnd.openxmlformats-officedocument.presentationml.slideshow"},
      {".xlsm", "application/vnd.ms-excel.sheet.macroEnabled.12"},
      {".pptm", "application/vnd.ms-powerpoint.presentation.macroEnabled.12"},
      {".docm", "application/vnd.ms-word.document.macroEnabled.12"},
      {".xlam", "application/vnd.ms-excel.addin.macroEnabled.12"},
      {".ppam", "application/vnd.ms-powerpoint.addin.macroEnabled.12"},
      {".xlsb", "application/vnd.ms-excel.sheet.binary.macroEnabled.12"},
      {".xps", "application/vnd.ms-xpsdocument"},
      {".xdp", "application/vnd.adobe.xdp+xml"},
      {".xfdf", "application/vnd.adobe.xfdf"},
      {".pki", "application/pkix-cert"},
      {".cer", "application/pkix-cert"},
      {".crl", "application/pkix-crl"},
      {".der", "application/x-x509-ca-cert"},
      {".pem", "application/x-x509-ca-cert"},
      {".p12", "application/x-pkcs12"},
      {".pfx", "application/x-pkcs12"},
      {".p7b", "application/x-pkcs7-certificates"},
      {".spc", "application/x-pkcs7-certificates"},
      {".p7r", "application/x-pkcs7-certreqresp"},
      {".p7c", "application/pkcs7-mime"},
      {".p7m", "application/pkcs7-mime"},
      {".p7s", "application/pkcs7-signature"},
      {".cbr", "application/x-cbr"},
      {".cbz", "application/x-cbz"},
      {".epub", "application/epub+zip"},
      {".fb2", "application/x-fictionbook+xml"},
      {".mobi", "application/x-mobipocket-ebook"},
      {".azw", "application/vnd.amazon.ebook"},
      {".lit", "application/x-ms-reader"},
      {".xar", "application/vnd.xara"},
      {".sit", "application/x-stuffit"},
      {".sea", "application/x-stuffit"},
      {".hqx", "application/mac-binhex40"},
      {".bin", "application/octet-stream"},
      {".dms", "application/octet-stream"},
      {".lha", "application/octet-stream"},
      {".lzh", "application/octet-stream"},
      {".arc", "application/octet-stream"},
      {".arj", "application/octet-stream"},
      {".zoo", "application/octet-stream"},
      {".cpt", "application/mac-compactpro"},
      {".wps", "application/vnd.ms-works"},
      {".wks", "application/vnd.ms-works"},
      {".wcm", "application/vnd.ms-works"},
      {".wdb", "application/vnd.ms-works"},
      {".xlc", "application/vnd.ms-excel"},
      {".xlm", "application/vnd.ms-excel"},
      {".xll", "application/vnd.ms-excel"},
      {".xlw", "application/vnd.ms-excel"},
      {".dir", "application/x-director"},
      {".dcr", "application/x-director"},
      {".dxr", "application/x-director"},
      {".fgd", "application/x-director"},
      {".swa", "application/x-director"},
      {".swf", "application/x-shockwave-flash"},
      {".wrl", "model/vrml"},
      {".vrml", "model/vrml"},
      {".xaf", "x-world/x-vrml"},
      {".xof", "x-world/x-vrml"},
      {".mpd", "application/vnd.ms-project"},
      {".mpt", "application/vnd.ms-project"},
      {".mda", "application/msaccess"},
      {".mdb", "application/msaccess"},
      {".mde", "application/msaccess"},
      {".adp", "application/msaccess"},
      {".mso", "application/octet-stream"},
      {".cat", "application/vnd.ms-pkiseccat"},
      {".stl", "application/vnd.ms-pki.stl"},
      {".sst", "application/vnd.ms-pki.certstore"},
      {".crt", "application/x-x509-ca-cert"},
      {".pko", "application/vnd.ms-pkipko"},
      {".chm", "application/vnd.ms-htmlhelp"},
      {".dot", "application/msword"},
      {".xla", "application/vnd.ms-excel"},
      {".xlc", "application/vnd.ms-excel"},
      {".xlm", "application/vnd.ms-excel"},
      {".xlt", "application/vnd.ms-excel"},
      {".xlw", "application/vnd.ms-excel"},
      {".pot", "application/vnd.ms-powerpoint"},
      {".ppa", "application/vnd.ms-powerpoint"},
      {".pps", "application/vnd.ms-powerpoint"},
      {".pwz", "application/vnd.ms-powerpoint"},
      {".vsd", "application/vnd.visio"},
      {".vst", "application/vnd.visio"},
      {".vsw", "application/vnd.visio"},
      {".vss", "application/vnd.visio"},
      {".vdx", "application/vnd.visio"},
      {".vtx", "application/vnd.visio"},
      {".vml", "application/vnd.visio"},
      {".wmf", "image/x-wmf"},
      {".emf", "image/x-emf"},
      {".cdr", "application/vnd.corel-draw"},
      {".cdt", "image/x-coreldrawtemplate"},
      {".cgm", "image/cgm"},
      {".cmx", "image/x-cmx"},
      {".dxf", "image/vnd.dxf"},
      {".dwg", "image/vnd.dwg"},
      {".fif", "application/fractals"},
      {".gbr", "application/rpki-ghostbusters"},
      {".pct", "image/pict"},
      {".pic", "image/pict"},
      {".pict", "image/pict"},
      {".psp", "application/octet-stream"},
      {".qti", "image/x-quicktime"},
      {".qtif", "image/x-quicktime"},
      {".rp", "image/vnd.rn-realpix"},
      {".svf", "image/vnd.dvb.service"},
      {".sgi", "image/sgi"},
      {".sid", "image/x-mrsid-image"},
      {".wpg", "application/x-wordperfect-graphic"},
      {".cur", "image/x-icon"},
      {".pcx", "image/x-pcx"},
      {".pnm", "image/x-portable-anymap"},
      {".pbm", "image/x-portable-bitmap"},
      {".pgm", "image/x-portable-graymap"},
      {".ppm", "image/x-portable-pixmap"},
      {".ras", "image/x-cmu-raster"},
      {".rgb", "image/x-rgb"},
      {".xbm", "image/x-xbitmap"},
      {".xpm", "image/x-xpixmap"},
      {".xwd", "image/x-xwindowdump"},
      {".psd", "image/vnd.adobe.photoshop"},
      {".ai", "application/postscript"},
      {".eps", "application/postscript"},
      {".ps", "application/postscript"},
      {".indd", "application/x-indesign"},
      {".mif", "application/vnd.mif"},
      {".fm", "application/vnd.framemaker"},
      {".book", "application/vnd.framemaker"},
      {".fnc", "application/vnd.frogans.fnc"},
      {".fpx", "image/vnd.fpx"},
      {".npx", "image/vnd.net-fpx"},
      {".dcr", "application/x-director"},
      {".dir", "application/x-director"},
      {".dxr", "application/x-director"},
      {".cst", "application/x-director"},
      {".cct", "application/x-director"},
      {".cxt", "application/x-director"},
      {".wml", "text/vnd.wap.wml"},
      {".wmlc", "application/vnd.wap.wmlc"},
      {".wmls", "text/vnd.wap.wmlscript"},
      {".wmlsc", "application/vnd.wap.wmlscriptc"},
      {".wbmp", "image/vnd.wap.wbmp"},
      {".ice", "x-conference/x-cooltalk"},
      {".jad", "text/vnd.sun.j2me.app-descriptor"},
      {".jnlp", "application/x-java-jnlp-file"},
      {".ser", "application/java-serialized-object"},
      {".class", "application/java-vm"},
      {".jar", "application/java-archive"},
      {".war", "application/java-archive"},
      {".ear", "application/java-archive"},
      {".hqx", "application/mac-binhex40"},
      {".cpt", "application/mac-compactpro"},
      {".oda", "application/oda"},
      {".smi", "application/smil"},
      {".smil", "application/smil"},
      {".pfa", "application/x-font-type1"},
      {".pfb", "application/x-font-type1"},
      {".pfm", "application/x-font-type1"},
      {".afm", "application/x-font-type1"},
      {".pcf", "application/x-font-pcf"},
      {".gsf", "application/x-font-ghostscript"},
      {".bdf", "application/x-font-bdf"},
      {".snf", "application/x-font-snf"},
      {".pfr", "application/font-tdpfr"},
      {".spl", "application/x-futuresplash"},
      {".tcl", "application/x-tcl"},
      {".tk", "application/x-tcl"},
      {".dssc", "application/dssc+der"},
      {".xdssc", "application/dssc+xml"},
      {".cdmia", "application/cdmi-capability"},
      {".cdmic", "application/cdmi-container"},
      {".cdmid", "application/cdmi-domain"},
      {".cdmio", "application/cdmi-object"},
      {".cdmiq", "application/cdmi-queue"},
      {".cu", "application/cu-seeme"},
      {".davmount", "application/davmount+xml"},
      {".dpg", "application/vnd.dpgraph"},
      {".es", "application/ecmascript"},
      {".emma", "application/emma+xml"},
      {".epub", "application/epub+zip"},
      {".exi", "application/exi"},
      {".gml", "application/gml+xml"},
      {".gpx", "application/gpx+xml"},
      {".gxf", "application/gxf"},
      {".hjson", "application/hjson"},
      {".ink", "application/inkml+xml"},
      {".inkml", "application/inkml+xml"},
      {".ipfix", "application/ipfix"},
      {".js", "application/javascript"},
      {".jsonml", "application/jsonml+json"},
      {".jsonld", "application/ld+json"},
      {".lostxml", "application/lost+xml"},
      {".mads", "application/mads+xml"},
      {".mods", "application/mods+xml"},
      {".n3", "text/n3"},
      {".n-triples", "application/n-triples"},
      {".nt", "application/n-triples"},
      {".owl", "application/owl+xml"},
      {".qps", "application/vnd.publishare-delta-tree"},
      {".raml", "application/raml+yaml"},
      {".rdf", "application/rdf+xml"},
      {".rif", "application/reginfo+xml"},
      {".rl", "application/resource-lists+xml"},
      {".rld", "application/resource-lists-diff+xml"},
      {".rs", "application/rls-services+xml"},
      {".rtf", "application/rtf"},
      {".sbml", "application/sbml+xml"},
      {".scq", "application/scvp-cv-request"},
      {".scs", "application/scvp-cv-response"},
      {".sdp", "application/sdp"},
      {".setpay", "application/set-payment-initiation"},
      {".setreg", "application/set-registration-initiation"},
      {".shf", "application/shf+xml"},
      {".sieve", "application/sieve"},
      {".sif", "application/vnd.acucorp"},
      {".silo", "model/mesh"},
      {".sml", "application/smil+xml"},
      {".srgs", "application/srgs"},
      {".srx", "application/sparql-results+xml"},
      {".ssml", "application/ssml+xml"},
      {".tei", "application/tei+xml"},
      {".teic", "application/tei+xml"},
      {".tfi", "application/thraud+xml"},
      {".tsd", "application/timestamped-data"},
      {".tsv", "text/tab-separated-values"},
      {".ttl", "text/turtle"},
      {".uri", "text/uri-list"},
      {".uris", "text/uri-list"},
      {".urls", "text/uri-list"},
      {".vxml", "application/voicexml+xml"},
      {".wgt", "application/widget"},
      {".wsdl", "application/wsdl+xml"},
      {".xop", "application/xop+xml"},
      {".xslt", "application/xslt+xml"},
      {".xspf", "application/xspf+xml"},
      {".yaml", "text/yaml"},
      {".yang", "application/yang"},
      {".yin", "application/yin+xml"},
      {".zip", "application/zip"},
      {".zst", "application/zstd"}};

  size_t dotPos = filename.find_last_of('.');
  std::string extension;

  if (dotPos != std::string::npos && dotPos != 0)
    extension = filename.substr(dotPos);
  else
    return "application/octet-stream";

  std::transform(extension.begin(), extension.end(), extension.begin(),
                 [](unsigned char c) { return std::tolower(c); });

  auto it = mimeTypes.find(extension);
  if (it != mimeTypes.end())
    return it->second;

  return "application/octet-stream";
}

} // namespace Netlet::Net
